on: [push]

jobs:
  build-secure-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - run: |
       echo "github.sha=$GITHUB_SHA
       docker build -t cnrtest.azurecr.io/k8sdemo:${{github.sha}} .
      
    - uses: Azure/container-scan@v0
      with:
        image-name: cnrtest.azurecr.io/k8sdemo:${{github.sha}}
    
    - uses: Azure/docker-login@v1
      with:
        login-server: cnrtest.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - run: docker push cnrtest.azurecr.io/k8sdemo:${{ github.sha }}


    - name: Post logs to appinsights
      uses: Azure/publish-security-assessments@v0
      with:
        scan-results-path: ${{ steps.container-scan.outputs.scan-report-path }}
        connection-string: ${{ secrets.AZ_APPINSIGHTS_CONNECTION_STRING }}
        subscription-token: ${{ secrets.AZ_SUBSCRIPTION_TOKEN }}
